/* ============LICENSE_START====================================================
 * org.onap.music.mdbc
 * =============================================================================
 * Copyright (C) 2018 AT&T Intellectual Property. All rights reserved.
 * =============================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END======================================================
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.onap.music.mdbc.proto;

/**
 * Protobuf type {@code musictestproto.Ack}
 */
public  final class Ack extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:musictestproto.Ack)
    AckOrBuilder {
  // Use Ack.newBuilder() to construct.
  private Ack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ack() {
    latency_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Ack(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              latency_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            latency_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              latency_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              latency_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        latency_ = java.util.Collections.unmodifiableList(latency_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.onap.music.mdbc.proto.MusicTestProto.internal_static_musictestproto_Ack_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.onap.music.mdbc.proto.MusicTestProto.internal_static_musictestproto_Ack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.onap.music.mdbc.proto.Ack.class, org.onap.music.mdbc.proto.Ack.Builder.class);
  }

  public static final int LATENCY_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> latency_;
  /**
   * <code>repeated int64 latency = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getLatencyList() {
    return latency_;
  }
  /**
   * <code>repeated int64 latency = 1;</code>
   */
  public int getLatencyCount() {
    return latency_.size();
  }
  /**
   * <code>repeated int64 latency = 1;</code>
   */
  public long getLatency(int index) {
    return latency_.get(index);
  }
  private int latencyMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getLatencyList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(latencyMemoizedSerializedSize);
    }
    for (int i = 0; i < latency_.size(); i++) {
      output.writeInt64NoTag(latency_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < latency_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(latency_.get(i));
      }
      size += dataSize;
      if (!getLatencyList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      latencyMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.onap.music.mdbc.proto.Ack)) {
      return super.equals(obj);
    }
    org.onap.music.mdbc.proto.Ack other = (org.onap.music.mdbc.proto.Ack) obj;

    boolean result = true;
    result = result && getLatencyList()
        .equals(other.getLatencyList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getLatencyCount() > 0) {
      hash = (37 * hash) + LATENCY_FIELD_NUMBER;
      hash = (53 * hash) + getLatencyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.onap.music.mdbc.proto.Ack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.onap.music.mdbc.proto.Ack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.onap.music.mdbc.proto.Ack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.onap.music.mdbc.proto.Ack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.onap.music.mdbc.proto.Ack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code musictestproto.Ack}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:musictestproto.Ack)
      org.onap.music.mdbc.proto.AckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onap.music.mdbc.proto.MusicTestProto.internal_static_musictestproto_Ack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onap.music.mdbc.proto.MusicTestProto.internal_static_musictestproto_Ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onap.music.mdbc.proto.Ack.class, org.onap.music.mdbc.proto.Ack.Builder.class);
    }

    // Construct using org.onap.music.mdbc.proto.Ack.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      latency_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.onap.music.mdbc.proto.MusicTestProto.internal_static_musictestproto_Ack_descriptor;
    }

    public org.onap.music.mdbc.proto.Ack getDefaultInstanceForType() {
      return org.onap.music.mdbc.proto.Ack.getDefaultInstance();
    }

    public org.onap.music.mdbc.proto.Ack build() {
      org.onap.music.mdbc.proto.Ack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.onap.music.mdbc.proto.Ack buildPartial() {
      org.onap.music.mdbc.proto.Ack result = new org.onap.music.mdbc.proto.Ack(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        latency_ = java.util.Collections.unmodifiableList(latency_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.latency_ = latency_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.onap.music.mdbc.proto.Ack) {
        return mergeFrom((org.onap.music.mdbc.proto.Ack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.onap.music.mdbc.proto.Ack other) {
      if (other == org.onap.music.mdbc.proto.Ack.getDefaultInstance()) return this;
      if (!other.latency_.isEmpty()) {
        if (latency_.isEmpty()) {
          latency_ = other.latency_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLatencyIsMutable();
          latency_.addAll(other.latency_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.onap.music.mdbc.proto.Ack parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.onap.music.mdbc.proto.Ack) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> latency_ = java.util.Collections.emptyList();
    private void ensureLatencyIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        latency_ = new java.util.ArrayList<java.lang.Long>(latency_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getLatencyList() {
      return java.util.Collections.unmodifiableList(latency_);
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public int getLatencyCount() {
      return latency_.size();
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public long getLatency(int index) {
      return latency_.get(index);
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public Builder setLatency(
        int index, long value) {
      ensureLatencyIsMutable();
      latency_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public Builder addLatency(long value) {
      ensureLatencyIsMutable();
      latency_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public Builder addAllLatency(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLatencyIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, latency_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 latency = 1;</code>
     */
    public Builder clearLatency() {
      latency_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:musictestproto.Ack)
  }

  // @@protoc_insertion_point(class_scope:musictestproto.Ack)
  private static final org.onap.music.mdbc.proto.Ack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.onap.music.mdbc.proto.Ack();
  }

  public static org.onap.music.mdbc.proto.Ack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ack>
      PARSER = new com.google.protobuf.AbstractParser<Ack>() {
    public Ack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ack(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Ack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ack> getParserForType() {
    return PARSER;
  }

  public org.onap.music.mdbc.proto.Ack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

